package medlife.com.br.model;

public enum OrderStatus {
    EMPTY,
    ITEMS_ADDED,
    CHECKOUT_STARTED,
    ORDER_CONFIRMED,
    ORDER_CANCELED,
    PAYMENT_PENDING,
    PAYMENT_CONFIRMED,
    PREPARING,
    READY_FOR_DELIVERY,
    OUT_FOR_DELIVERY,
    DELIVERED,
    COMPLETED,
    REFUNDED,
    PRESCRIPTION_REQUIRED,
    PRESCRIPTION_APPROVED,
    PRESCRIPTION_REJECTED
} 