package medlife.com.br.model

import com.google.firebase.Timestamp
import com.google.firebase.firestore.ServerTimestamp

data class Usuario(
    var uid: String? = null,
    var nome: String? = null,
    var email: String? = null,
    var genero: String? = null,
    var otherGender: String? = null,
    var phoneNumber: String? = null,
    var dateOfBirth: String? = null,
    var cpf: String? = null,
    var endereco: List<Map<String, Any>>? = null,
    var orders: List<Order>? = null,
    @ServerTimestamp
    var criadoEm: Timestamp? = null,
    var lastLogin: Timestamp? = null,
    var enderecoPrincipal: Int = 0
) {
    // Required empty constructor for Firestore is generated by default parameters
}
